### ISSUE TITLE
Some files are missing...

### ISSUE THREAD

**Issue by ghost** [slidenerd/materialtest#2]
Hi, i recently checkout this project and i get these errors: 
1. Are missing ic_action_search, ic_action_trending.
2. In Requestor class, "reference to JsonObjectRequest is ambiguous ..."
   
   JsonObjectRequest request = new JsonObjectRequest(Request.Method.GET,
                 url,
                 null, requestFuture, requestFuture);

Thanks

**Comment by slidenerd** [comment]
ok i ll see to it the images are added, thanks

**Comment by Deeptimay** [comment]
Same problem here. ..

In Requestor class, "reference to JsonObjectRequest is ambiguous ..."

JsonObjectRequest request = new JsonObjectRequest(Request.Method.GET,
url,
null, requestFuture, requestFuture);

Thanks in adv.

**Comment by slidenerd** [comment]
This ll help you, https://www.youtube.com/watch?v=WbWR-nylvS8

**Comment by Deeptimay** [comment]
thankxx buddy. .. u are awesome.. keep it up! (Y)

**Comment by ghost** [comment]
:D Thanks a lot. I didn't googled this error because i was thinking that you forget to add some files (like these icons) )) now is working!

**Comment by slidenerd** [comment]
the images working now? I may have added them but not sure

**Comment by ghost** [comment]
Yes they working!

**Comment by Deeptimay** [comment]
yup. .. perfectly (Y)

**Comment by Sitarman** [comment]
Nice work Viz really appreciate the hard work you put into your tutorials.
