### ISSUE TITLE
I have an issue with JsonObjectRequest !

### ISSUE THREAD

**Issue by Mansourali** [slidenerd/materialtest#3]
Hi Vivs,
I just starting following your tutorial on YouTube when I facing this error with the JsonObjectRequest 
The error said "Cannot resolve the constructor" 
The constructor does not take the null for the JSONObject for the following constructor as in the documentation:

public JsonObjectRequest(int method,
                         String url,
                         JSONObject jsonRequest,
                         Response.Listener<JSONObject> listener,
                         Response.ErrorListener errorListener)

when I remove the JSONObject argument the request is compile but it does not succeed in getting the Json 
are the volley lib getting updated or I did some thing wrong here?
thanks in advance 
[Screen shot of the error](https://cloud.githubusercontent.com/assets/4660941/6771315/14af002c-d117-11e4-9113-03e0345d90af.png)

**Comment by vikrantchoudhary** [comment]
Hi Vivs,
 Even i have the same issue. Could you please let us know the solution?

**Comment by vikrantchoudhary** [comment]
mine issue has been fixed. I have the updated volley library & same ambiguous issue  which you have already discussed  in https://www.youtube.com/watch?v=WbWR-nylvS8

**Comment by Mansourali** [comment]
thanks vikrantchoudhary, appreciate your help now it's compile
